export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE";

export const GET_TOP_RATED_MOVIES_REQUEST = "GET_TOP_RATED_MOVIES_REQUEST";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_FAILURE = "GET_TOP_RATED_MOVIES_FAILURE";

export const GET_BEST_OF_LIVE_EVENTS_REQUEST = "GET_BEST_OF_LIVE_EVENTS_REQUEST";
export const GET_BEST_OF_LIVE_EVENTS_SUCCESS = "GET_BEST_OF_LIVE_EVENTS_SUCCESS";
export const GET_BEST_OF_LIVE_EVENTS_FAILURE = "GET_BEST_OF_LIVE_EVENTS_FAILURE";